layout_spectrum: 0.492422
typography_spectrum: 0.9572316
color:
  saturation: 0.703028
  lightness: 0.5315058
  brandStrength: 0.3297603
  rhythmicContrast: 0.5479656
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
name: SoDamnPriviledgedtoBeHere
